org.gradle.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.parallel=false
org.gradle.caching=true
android.enableDexingArtifactTransform.parallel=false

# Workaround for jlink / JdkImageTransform "ModuleTarget is malformed" error
android.experimental.useJdkImage=false
android.useFullClasspathForSystemModules=true
android.jdk.include-system-modules=false
android.enableJdkImageTransform=false
# Additional flag for newer AGP versions
android.includeJdkImage=false
